run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Disabled by default
    - copyloopvar
    - exhaustive
    - gofmt
    - gocritic
    - goimports
    - gosec
    - intrange
    - misspell
    - nilerr
    - nolintlint
    - paralleltest
    - unconvert
    - unparam
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/karamaru-alpha/mocka
